--# local client = vim.lsp.start_client({
--#   name = "educationallsp",
--#   cmd = {"/Users/corvi/repos/go/educationallsp/main"},
--# })
--#
--# if not client then
--#   vim.notify("Hey you didn't do the client things good")
--#   return
--# end
--#
--# vim.api.nvim_create_autocmd("FileType", {
--#   pattern = "markdown",
--#   callback = function()
--#     vim.lsp.buf_attach_client(0, client)
--#   end,
--# })
